name: matroid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.6.0
  file_picker: ^10.3.0
  path_provider: ^2.1.5
  crypto: ^3.0.7
  shared_preferences: ^2.5.0
  flutter_code_editor: ^0.3.5
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  flutter_markdown_plus: ^1.0.7
  flutter_math_fork: ^0.7.4
  printing: ^5.14.0
  pdf: ^3.11.3
  markdown: ^7.3.0
  web: ^1.1.1
  fl_chart: ^1.1.0
  image_picker: ^1.2.1
  video_player: ^2.11.0
  chewie: ^1.13.0
  media_kit: ^1.1.11
  media_kit_video: ^1.1.11
  media_kit_libs_video: ^1.0.4
  accessibility_tools: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/bin/
    - assets/fonts/
  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700
        - asset: assets/fonts/OpenDyslexic-Italic.otf
          style: italic
        - asset: assets/fonts/OpenDyslexic-BoldItalic.otf
          weight: 700
          style: italic
    - family: OpenDyslexicMono
      fonts:
        - asset: assets/fonts/OpenDyslexicMono-Regular.otf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
